Models/SMSTextMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMSService.Models
{
    public class SMSTextMessage
    {
        // ID property for Entity Framework integration
        public int Id { get; set; }

        // Area Code property for area code of contact with validation
        [Display(Name = "Area Code")]
        [Required(ErrorMessage = "You must enter a valid area code e.g. 085")]
        [RegularExpression("^08[3-9]$", ErrorMessage = "Please enter a valid 3 digit area code")]
        public string AreaCode { get; set; }

        // Phone Number property for phone number of contact with validation
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "You must enter a valid phone number e.g. 1234567")]
        [RegularExpression("^[0-9][0-9][0-9][0-9][0-9][0-9][0-9]$", ErrorMessage = "Please enter a valid 7 digit phone number")]
        public string PhoneNumber { get; set; }

        // Text Content property for text content of message with validation
        [Display(Name = "Message")]
        [Required(ErrorMessage = "You have to write something!")]
        [StringLength(140, MinimumLength = 1, ErrorMessage = "There must be between 1 and 140 characters in your message.")]
        public string TextContent { get; set; }
    }
}

Controllers/SMSTextMessageController.cs
using System.Web.Mvc;
using SMSService.Models;
namespace SMSService.Controllers
{
    public class SMSTextMessageController : Controller
    {
        // GET: SMSTextMessage
        public ActionResult Index()
        {
            return View();
        }

        // POST: SMSTextMessage
        [HttpPost]
        public ActionResult Index(SMSTextMessage sms)
        {
            if (ModelState.IsValid)
            {
                // findContact returns error, an error message is broadcast to the screen.
                // otherwise it broadcasts a success message
                    Contacts contactsIndex = new Contacts();
                    string findContact = contactsIndex.findContact(sms.AreaCode, sms.PhoneNumber);

                    if (findContact == "error")
                    {
                        ViewData["SuccessMsg"] = "Error. Contact does not exist. Goto contacts page above.";
                    }
                    else
                    {
                        ViewData["SuccessMsg"] = "Message was successfully sent.";
                    }
            }
            return View(sms);
        }
    }
}

Views/SMSTextMessage/Index.cshtml
@model SMSService.Models.SMSTextMessage
@{
    ViewBag.Title = "Index";
}

@using(Html.BeginForm("Index", "SMSTextMessage", FormMethod.Post))
        {
            <h4>SMS Service</h4>
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.AreaCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AreaCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AreaCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TextContent, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.TextContent, new { @class = "form-control", @rows = "10", @cols = "50" })
                    @Html.ValidationMessageFor(model => model.TextContent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Send Message" class="btn btn-default" />
                </div>
            </div>


            if (ViewData["SuccessMsg"] != null)
            {
                <div class="success">@ViewData["SuccessMsg"]</div>
            }

        
}
@section Scripts {
@Scripts.Render("~/bundles/jqueryval")
}